"""Regression guard: standup's "Next up" delivers the three rows it promises.

Section 5 states a row count — "the top 3 open `human_gate: none` cards by
value score" — and bounds the engine's output with a fixed `head -5`: two
lines of table chrome plus three rows.

That arithmetic only holds while the table is the first thing on stdout. It
is not, whenever any card is claimed: `engine.render_active_banner` prepends
a one-line `ACTIVE: …` soft-lock warning **to stdout** on every open-queue
query, `--ready` included. The budget then spends three lines on chrome and
forwards two rows — a silent 33% cut to the only forward-looking section,
in exactly the deck state standup exists to report on. See the card
`standup-next-up-shows-two-cards-not-three-whenever-any-card-is-active`.

This guard executes the shipped pipeline rather than restating it: the bash
block is extracted verbatim from each SKILL.md and only the `goc` token is
rebound to this checkout's engine, so the `grep`/`head` bound under test is
the one consumers actually run.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Source of truth first; the rest are mechanical mirrors regenerated by
# `scripts/sync_plugin_assets.py` (claude/codex) and
# `scripts/port_skills_to_openclaw.py` (openclaw). A mirror missing from a
# partial checkout is skipped, not failed.
STANDUP_COPIES = [
    ROOT / "goc" / "templates" / "skills" / "standup" / "SKILL.md",
    ROOT / ".claude" / "skills" / "standup" / "SKILL.md",
    ROOT / ".codex" / "skills" / "standup" / "SKILL.md",
    ROOT / "claude-plugin" / "skills" / "standup" / "SKILL.md",
    ROOT / "codex-plugin" / "skills" / "standup" / "SKILL.md",
    ROOT / "openclaw-plugin" / "skills" / "standup" / "SKILL.md",
]

PROMISED_ROWS = 3

_SECTION_RE = re.compile(
    r"^## Section 5 — Next up\n(.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL
)
_FENCE_RE = re.compile(r"```bash\n(.*?)\n```", re.DOTALL)

_CARD = """---
title: {title}
summary: probe card {title}
status: {status}
stage: null
contribution: high
created: "2026-09-01T00:00:00Z"
closed_at: null
human_gate: none
advances: []
advanced_by: []
tags: [infra]
definition_of_done: |
  - [ ] MECHANICAL: something concrete happens.
{extra}---

# {title}

Real body text so the card is not an unauthored scaffold.
"""


def _section_5_command(path: Path) -> str | None:
    section = _SECTION_RE.search(path.read_text(encoding="utf-8"))
    if section is None:
        return None
    blocks = _FENCE_RE.findall(section.group(1))
    return blocks[0].strip() if blocks else None


def _build_deck(root: Path, *, with_active: bool) -> None:
    deck = root / ".game-of-cards" / "deck"
    deck.mkdir(parents=True)
    for name in ("alpha", "bravo", "charlie", "delta", "echo"):
        card = deck / f"ready-{name}"
        card.mkdir()
        (card / "README.md").write_text(
            _CARD.format(title=f"ready-{name}", status="open", extra=""),
            encoding="utf-8",
        )
    if with_active:
        card = deck / "in-flight-card"
        card.mkdir()
        (card / "README.md").write_text(
            _CARD.format(
                title="in-flight-card",
                status="active",
                extra="worker: {who: someone, where: main}\n",
            ),
            encoding="utf-8",
        )


def _run(command: str, cwd: Path) -> str:
    """Run the shipped block with `goc` rebound to this checkout's engine."""
    bound = re.sub(
        r"(?<![\w-])goc(?=\s)",
        f"{sys.executable} -m goc.cli",
        command,
        count=1,
    )
    return subprocess.run(
        ["sh", "-c", bound],
        cwd=cwd,
        capture_output=True,
        text=True,
        env={"PATH": "/usr/bin:/bin", "PYTHONPATH": str(ROOT), "HOME": str(cwd)},
    ).stdout


def _rows(out: str) -> list[str]:
    return [line for line in out.splitlines() if line.startswith("ready-")]


class StandupNextUpRowBudgetTest(unittest.TestCase):
    def test_template_has_a_section_5_command(self) -> None:
        self.assertIsNotNone(
            _section_5_command(STANDUP_COPIES[0]),
            "goc/templates/skills/standup/SKILL.md: no '## Section 5 — Next up' "
            "bash block found — if the section was renamed, retarget this guard "
            "rather than deleting it.",
        )

    def test_row_budget_survives_the_active_card_banner(self) -> None:
        """The promised row count must not depend on whether a card is claimed."""
        offenders: list[str] = []
        for path in STANDUP_COPIES:
            if not path.is_file():
                continue
            command = _section_5_command(path)
            if command is None:
                continue
            for label, with_active in (("no active card", False), ("an active card", True)):
                with tempfile.TemporaryDirectory() as tmp:
                    root = Path(tmp)
                    _build_deck(root, with_active=with_active)
                    got = _rows(_run(command, root))
                if len(got) != PROMISED_ROWS:
                    offenders.append(
                        f"{path.relative_to(ROOT)} with {label}: "
                        f"{len(got)} rows, expected {PROMISED_ROWS}"
                    )
        self.assertEqual(
            [],
            offenders,
            "standup 'Next up' must forward the 3 rows its prose promises "
            "regardless of deck state. The engine writes a conditional "
            "one-line `ACTIVE:` banner to stdout whenever a card is claimed, "
            "so a bare `head -5` spends a row on chrome — filter the banner "
            "before the bound. Edit goc/templates/skills/standup/SKILL.md, "
            "then re-run scripts/sync_plugin_assets.py and "
            "scripts/port_skills_to_openclaw.py.",
        )


if __name__ == "__main__":
    unittest.main()
