"""Regression guard: standup's "Next up" section selects with the engine's pull predicate.

Section 5 of the standup skill promises "the cards `Skill(pull-card)` would
pick next". `Skill(pull-card)` picks with `goc --ready`, i.e. the engine's
`card_is_ready`: `status: open` AND not a draft scaffold AND
`human_gate: none` AND no active `waiting_on` / `waiting_until` overlay.

The section used to ship bare `goc` — `--status open` and nothing else. That
is one of the four conjuncts, and because the queue is value-sorted while
human-gated epics carry the deck's top values, the three rows it surfaced were
systematically the *least* pullable cards present. See the card
`standup-next-up-section-lists-cards-pull-card-would-never-pick`.

The substitution is one token, which is exactly why it is easy to lose again
in a rewrite of this section. This guard pins it across the source-of-truth
template AND every shipped mirror, so a hand-edit of a mirror (which the
pre-commit sync would overwrite) or a template edit that drops the flag turns
the build red rather than rotting silently.
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Source of truth first; the rest are mechanical mirrors regenerated by
# `scripts/sync_plugin_assets.py` (claude/codex) and
# `scripts/port_skills_to_openclaw.py` (openclaw). A mirror that is absent in
# a partial checkout is skipped, not failed — the template assertion is the
# one that must always run.
STANDUP_COPIES = [
    ROOT / "goc" / "templates" / "skills" / "standup" / "SKILL.md",
    ROOT / ".claude" / "skills" / "standup" / "SKILL.md",
    ROOT / ".codex" / "skills" / "standup" / "SKILL.md",
    ROOT / "claude-plugin" / "skills" / "standup" / "SKILL.md",
    ROOT / "codex-plugin" / "skills" / "standup" / "SKILL.md",
    ROOT / "openclaw-plugin" / "skills" / "standup" / "SKILL.md",
]

_SECTION_RE = re.compile(
    r"^## Section 5 — Next up\n(.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL
)
_FENCE_RE = re.compile(r"```bash\n(.*?)\n```", re.DOTALL)


def _section_5_commands(path: Path) -> list[str]:
    """Every shell command inside the template's "Section 5 — Next up" block."""
    section = _SECTION_RE.search(path.read_text(encoding="utf-8"))
    if section is None:
        return []
    return [block.strip() for block in _FENCE_RE.findall(section.group(1))]


class StandupNextUpPredicateTest(unittest.TestCase):
    def test_template_has_a_section_5_command(self) -> None:
        """The template must carry the section this guard pins."""
        commands = _section_5_commands(STANDUP_COPIES[0])
        self.assertTrue(
            commands,
            "goc/templates/skills/standup/SKILL.md: no '## Section 5 — Next up' "
            "bash block found — if the section was renamed, retarget this guard "
            "rather than deleting it.",
        )

    def test_next_up_selects_with_the_ready_predicate(self) -> None:
        offenders: list[str] = []
        for path in STANDUP_COPIES:
            if not path.is_file():
                continue
            for command in _section_5_commands(path):
                if "--ready" not in command:
                    offenders.append(f"{path.relative_to(ROOT)}: {command!r}")
        self.assertEqual(
            [],
            offenders,
            "standup 'Next up' must select with `goc --ready` (the predicate "
            "pull-card uses); a bare queue query lists human-gated and impeded "
            "cards that pull-card will never pick. Edit "
            "goc/templates/skills/standup/SKILL.md, then re-run "
            "scripts/sync_plugin_assets.py and scripts/port_skills_to_openclaw.py.",
        )


if __name__ == "__main__":
    unittest.main()
